### PR TITLE
Change to internal URLDownloader

### PR DESCRIPTION
**Pull request by tobiasdiez**
But also results in SSL handshake error.

- [ ] Change in CHANGELOG.md described
- [ ] Tests created for changes
- [ ] Screenshots added (for bigger UI changes)
- [ ] Manually tested changed features in running JabRef
- [ ] Check documentation status (Issue created for outdated help page at [help.jabref.org](https://github.com/JabRef/help.jabref.org/issues)?)
- [x] If you changed the localization: Did you run `gradle localizationUpdate`?

### CODE REVIEW

**Comment by koppor** [comment]
🎉

**Comment by Joeran** [comment]
about the SSL problem:  this is a know problem on the side of Mr. DLib. When you visit e.g. https://api.mr-dlib.org/v1/documents/gesis-smarth-0000003284/related_documents/ in your browser, you get the same security warning. 
We don't have this problem on our Beta and Dev server, see e.g. https://api-beta.mr-dlib.org/v1/documents/gesis-smarth-0000003284/related_documents/

However, we plan to update to a new production server in the next couple of weeks and then the SSL error will be automatically gone. Therefore, we will not fix the problem on the current production server. I am not seeing any problem in this, because there is no sensitive information submitted that requires encryption.

**Comment by tobiasdiez** [comment]
Ok, in this case I would propose that you use the URL for the dev server in JabRef until the SSL certificate issues are fixed on production.

**Comment by Joeran** [comment]
> Ok, in this case I would propose that you use the URL for the dev server in JabRef until the SSL certificate issues are fixed on production.

are we talking about using the DEV system as long as we are still developing, or about using it when finally releasing the new JabRef version to the public? In latter case: why is the ssl error a problem (as long as the exception is properly caught)? using the dev or beta server means more errors in the recommendations (there is a reason that the beta system is called a beta system and the production system a production system), more downtimes during which JabRef users cannot received recommendations (because our beta server is more often down than the production system), slower responses (because the beta server is slower than production), and we cannot do any logging on the side of Mr. DLib because we only log data on the production system.

**Comment by tobiasdiez** [comment]
Ok, if you manage to perform the request and get a suitable response even with an invalid SSL certificate, then this would be also ok with me. But right now the recommender system is unusable in JabRef exactly because the SSL exception occurs. (And I think that changing `api` to `api-beta` is the easiest solution).

**Comment by koppor** [comment]
- [ ] Should the users be able to configure the endpoint so that they can switch from production to DEV?

Site note: In JabRef, we use successfully [letsencrypt](https://letsencrypt.org/), but this doesn't seem to be the issue if you upgrade the PROD server soon. I agree regarding the sensitive information. I wonder why SSL is used at all, but I also agree that no user wants that data to be transferred over wire in plain text.

**Pull request merged**
